export const products = [
    {
        name: "Hotdog",
        type: "hot, hotdog",
        combo_option_type: "main",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Mozzarella Sticks",
        type: "hot",
        combo_option_type: "",
        default_price: 3,
        image_path: "",
    },
    {
        name: "Pretzel",
        type: "hot",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Pepperoni Slice",
        type: "hot, pizza",
        combo_option_type: "main",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Cheese Slice",
        type: "hot, pizza",
        combo_option_type: "main",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Coke",
        type: "drink",
        combo_option_type: "drink",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Diet Coke",
        type: "drink",
        combo_option_type: "drink",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Sprite",
        type: "drink",
        combo_option_type: "drink",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Root Beer",
        type: "drink",
        combo_option_type: "drink",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Mountain Dew",
        type: "drink",
        combo_option_type: "drink",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Fruit Punch",
        type: "drink",
        combo_option_type: "drink",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Orange Pineapple",
        type: "drink",
        combo_option_type: "drink",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Grape Juice",
        type: "drink",
        combo_option_type: "drink",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Caprisun",
        type: "drink",
        combo_option_type: "drink",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Water",
        type: "drink",
        combo_option_type: "drink",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Yellow Gatorade",
        type: "drink",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Red Gatorade",
        type: "drink",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Blue Gatorade",
        type: "drink",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Ice Cream Sandwich",
        type: "frozen",
        combo_option_type: "",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Ice Cream Cone",
        type: "frozen",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Snickers",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "3 Musketeers",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Skittles",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Starburst",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "KitKat",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Reeses",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Twix",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Milky Way",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Hersheys",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Crunch",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Butterfingers",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "100 Grand",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Babe Ruth",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Funsize Skittles",
        type: "candy",
        combo_option_type: "",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Fruit Snacks",
        type: "candy",
        combo_option_type: "",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Granola Bars",
        type: "candy",
        combo_option_type: "",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Nacho Cheese Doritos",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Cool Ranch Doritos",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Fritos Original",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Chili Fritos",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "BBQ Lays",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Sour Cream & Onion Lays",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Classic Lays",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Cheetos",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Ruffles",
        type: "chips",
        combo_option_type: "chips",
        default_price: 1,
        image_path: "",
    },
    {
        name: "Dr. Pepper",
        type: "drink",
        combo_option_type: "drink",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Pretzel with Cheese",
        type: "hot",
        combo_option_type: "",
        default_price: 2.5,
        image_path: "",
    },
    {
        name: "Chocolate M&Ms",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Peanut Butter M&Ms",
        type: "candy",
        combo_option_type: "",
        default_price: 2,
        image_path: "",
    },
    {
        name: "Chick-fil-A Sandwich",
        type: "hot",
        combo_option_type: "",
        default_price: 7,
        image_path: "",
    },
];

export const combos = [
    {
        name: "Hotdog Meal Deal",
        default_price: 4,
        main_item_type: "hotdog",
        main_item_quantity: 1,
    },
    {
        name: "Pizza Meal Deal",
        default_price: 4,
        main_item_type: "pizza",
        main_item_quantity: 1,
    },
];

export const users = [
    {
        username: "mbruffey",
        first_name: "Matthew",
        last_name: "Bruffey",
        pin: "0810",
    },
    {
        username: "abrombacher",
        first_name: "Anja",
        last_name: "Brombacher",
        pin: "0614",
    },
    {
        username: "bdelich ",
        first_name: "Blake",
        last_name: "Delich",
        pin: "0706",
    },
    {
        username: "cflodstrom",
        first_name: "Carlos",
        last_name: "Flodstrom",
        pin: "0207",
    },
    {
        username: "jgoshgarian ",
        first_name: "Joe",
        last_name: "Goshgarian",
        pin: "0123",
    },
    {
        username: "ahuang",
        first_name: "Aaron",
        last_name: "Huang",
        pin: "0407",
    },
    {
        username: "bjohnson",
        first_name: "Brandt",
        last_name: "Johnson",
        pin: "0202",
    },
    {
        username: "lkulikova",
        first_name: "Liza",
        last_name: "Kulikova",
        pin: "0928",
    },
    {
        username: "glegoff",
        first_name: "Giselle",
        last_name: "Legoff",
        pin: "0430",
    },
    {
        username: "tmcleish",
        first_name: "Tava",
        last_name: "McLeish",
        pin: "0709",
    },
    {
        username: "jnayrath",
        first_name: "Jenny",
        last_name: "Nayrath",
        pin: "0108",
    },
    {
        username: "mpage",
        first_name: "Megan",
        last_name: "Page",
        pin: "0104",
    },
    {
        username: "jqin",
        first_name: "Jane",
        last_name: "Qin",
        pin: "0126",
    },
    {
        username: "lraisanen",
        first_name: "Lydia",
        last_name: "Raisanen",
        pin: "0220",
    },
    {
        username: "tstephens",
        first_name: "Tyler",
        last_name: "Stephens",
        pin: "0528",
    },
    {
        username: "gvikander",
        first_name: "Grant",
        last_name: "Vikander",
        pin: "0908",
    },
    {
        username: "evillar",
        first_name: "Eli",
        last_name: "Villar",
        pin: "0515",
    },
    {
        username: "lwilliams",
        first_name: "Lily",
        last_name: "Williams",
        pin: "0205",
    },
]